**import numpy as np**

In [1]:
import numpy as np

In [5]:
one_d_array = np.array([1,2,3])

In [6]:
one_d_array

array([1, 2, 3])

In [10]:
print(one_d_array.shape)
print(one_d_array.ndim)

(3,)
1


In [11]:
arr1 = np.array([[1,2,3],[4,5,5]])

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 5]])

## numpy vs list

In [13]:
#less memeory 

In [14]:
import sys 

In [16]:
sl = [1,2,3,4,5,6,7]
print(len(sl))

7


In [18]:
import sys

# declaring a list of 10 elements  
sample_list = [0,1,2,3,4,5,6,7,8,9] 

print("Length of List array: ",len(sample_list))

print("Type of array: ",type(sample_list))

print("Memory consumption by an element in the array: ",
        sys.getsizeof(sample_list[0]))

print("Memory usage by list array: ",
        (sys.getsizeof(sample_list[0]))*len(sample_list))


numpy_array = np.array([0,1,2,3,4,5,6,7,8,9])

print("Length of NumPy array: ",len(numpy_array))

print("Type of array: ",type(numpy_array))

print("Memory consumption by an element in the array: ",
        numpy_array.itemsize)

print("Memory usage by list array: ",
        numpy_array.itemsize*numpy_array.size)




Length of List array:  10
Type of array:  <class 'list'>
Memory consumption by an element in the array:  28
Memory usage by list array:  280
Length of NumPy array:  10
Type of array:  <class 'numpy.ndarray'>
Memory consumption by an element in the array:  4
Memory usage by list array:  40


In [19]:
# declaring a list 
ls =[11, 12, 13] 
  
# converting the list into a Numpy array 
arr = np.array(ls) 
  
try: 
    # adding 4 to each element of list 
    ls = ls + 4
      
except(TypeError): 
    print("Lists don't support list + int") 
  
# now on array 
try: 
    # adding 4 to each element of Numpy array 
    arr = arr + 4
  
    # printing the Numpy array 
    print("Modified Numpy array: ",arr) 
      
except(TypeError): 
    print("Numpy arrays don't support list + int") 


Lists don't support list + int
Modified Numpy array:  [15 16 17]


In [20]:

# Intializing the array with ones
ones_array = np.ones((3)) # Default dtype = float
print(ones_array)

ones2d_array = np.ones((2,3) , dtype=int)
print('\n',ones2d_array)


[1. 1. 1.]

 [[1 1 1]
 [1 1 1]]


In [21]:

# Intializing the array with zeros
zeros_array = np.zeros((3,3)) # Default dtype = float
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
random_array = np.random.random((3))
print(random_array)


[0.04291298 0.38809569 0.55843199]


In [26]:

random_array = np.random.random((3))
print(random_array)


[0.52663574 0.18897739 0.29319831]


In [27]:
# 2 d array with random values
random_array2D = np.random.random((3,3))
print("\n")
print(random_array2D)




[[0.55036753 0.1956091  0.31965408]
 [0.04181547 0.96970528 0.00154031]
 [0.67953439 0.12260491 0.31001926]]


In [28]:
# To get an array with specified input element of desired shape
array = np.full((3,3),20)
print(array)


[[20 20 20]
 [20 20 20]
 [20 20 20]]


In [30]:
# Print an identity matrix
identity_array = np.identity(6)
print(identity_array)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [31]:
# Array with values from 0 to 5
array_with_arange = np.arange(5)
array_with_arange


array([0, 1, 2, 3, 4])

In [33]:

# create an array with elements from 5 to 10 (exclusive)
# Parameters for the function - np.arange(start, stop, step, dtype)
array1 = np.arange(5, 10)
print(array1)


[5 6 7 8 9]


In [34]:
# create an array with elements from 5 to 15 with stepsize 2
array2 = np.arange(5, 15, 2)
print(array2)


[ 5  7  9 11 13]


In [35]:
# create an array with 3 elements between 5 and 10
linspace_array1 = np.linspace(5, 10, 20)

print(linspace_array1)


[ 5.          5.26315789  5.52631579  5.78947368  6.05263158  6.31578947
  6.57894737  6.84210526  7.10526316  7.36842105  7.63157895  7.89473684
  8.15789474  8.42105263  8.68421053  8.94736842  9.21052632  9.47368421
  9.73684211 10.        ]


In [37]:
# create an array of 5 elements between 2.0 and 3.0 excluding the endpoint
linspace_array2 = np.linspace(2.0, 3.0, num=5, endpoint=False)
print(linspace_array2)


[2.  2.2 2.4 2.6 2.8]


In [38]:

# create an array of 5 elements between 2.0 and 3.0 with the step size included
linspace_array3 = np.linspace(2.0, 3.0, num=5, retstep=True)
print(linspace_array3)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)


In [39]:
# Create list
my_list = [2,4,6,8,10]

# convert python list into numpy array
my_array = np.asarray(my_list)

# printing my_array
print(my_array)

# printing the type of my_array
print(type(my_array))


[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [40]:
# convert tuple to ndarray
my_tuple = (1,2,3) 
array = np.asarray(my_tuple) 
print(array)


[1 2 3]


## Indexing and slicing of array

In [42]:
# Accessing element in 1 d numpy array
data = np.array([1, 3, 5,7,9])
print(data[0])
print(data[1])

# Accessing element through negative indexing
print(data[-1])
print(data[-2])



1
3
9
7


In [43]:
# Slice 1 d array
#start, stop, step
print(data[0:3])
print(data[0:2])
print(data[:2])


[1 3 5]
[1 3]
[1 3]


In [44]:
# Print all elements of array
num_data = np.array([11, 22, 33,44,55,66,77,88,99])
print(num_data[:])

# Use step size=1
print(num_data[::1])# start and stop parameters is unspecified

# Use step size=2
print(num_data[::2])

#Print all elements in reverse order
print(num_data[::-1])


[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]
[11 33 55 77 99]
[99 88 77 66 55 44 33 22 11]


In [45]:
# retrieving elements from a 2-D array

data = np.array([[1,2,3],[4,5,6]])
print(data[0,1])
print(data[1,2])


2
6


In [46]:

data = np.array([[11,22,33],[44,55,66],[77,88,99]])
# Print entire array
print(data)

# Print first row
print("\n",data[0])

# Print Second row only
print("\n",data[1])


[[11 22 33]
 [44 55 66]
 [77 88 99]]

 [11 22 33]

 [44 55 66]


In [47]:
# Print first column only
print("\n",data[:,:1:1])

# Print First column with step size
print("\n",data[0::2,0:1])



 [[11]
 [44]
 [77]]

 [[11]
 [77]]


In [48]:
# For 3-D array slicing the format is array[index,row,column]
a = np.array([[[1,2],[3,4],[5,6]],
             [[7,8],[9,10],[11,12]],
             [[13,14],[15,16],[17,18]]])
# print(a)
print(a[0:2])
print(a[0:2,1:,1:])


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 4]
  [ 6]]

 [[10]
  [12]]]


## Array manipulation

In [49]:
array1 = np.array([1, 2, 3, 4, 5, 6])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns
result = np.reshape(array1, (2, 3))
print(result)

# reshape a 1D array into a 2D array 
# with 3 rows and 2 columns
result = np.reshape(array1, (3, 2))
print("\n",result)


[[1 2 3]
 [4 5 6]]

 [[1 2]
 [3 4]
 [5 6]]


In [50]:
# Reshaping 1 D array into 3 D array
# create a 1D array
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape the 1D array to a 3D array
result = np.reshape(array1, (2, 2, 2))

# print the new array
print("1D to 3D Array: \n",result)


1D to 3D Array: 
 [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


In [51]:
originalArray = np.array([[1, 2], [3, 4],[5,6]])
print(originalArray)

# swaps the rows and columns of an array
transposedArray = np.transpose(originalArray)

print(transposedArray)


[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [52]:
# creating an input array
myarray = np.array([[1,2,3],[4,5,6]])

# to flatten the array in F-order
print(myarray.flatten('k'))



[1 2 3 4 5 6]


In [53]:
# creating an input array
myarray = np.array([[1,2,3],[4,5,6]])

# to flatten the array in F-order
print(myarray.flatten('f'))



[1 4 2 5 3 6]


In [54]:
# Create NumPy array
my_arr = np.array([ [0,1], [2,3] ])
# Resize the numpy array using resize method
my_arr.resize( (2, 3) )

print(my_arr)



[[0 1 2]
 [3 0 0]]


In [56]:

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row


array([[2, 3],
       [4, 5],
       [6, 7]])

In [57]:
###Lets multiply two arrays
a=np.array([[4,3,2,2],[2,3,3,4]])
print(a)
b=np.array([[3,1,4,2],[4,4,1,0]])
print("\n",b)
np.multiply(a,b)


[[4 3 2 2]
 [2 3 3 4]]

 [[3 1 4 2]
 [4 4 1 0]]


array([[12,  3,  8,  4],
       [ 8, 12,  3,  0]])

In [58]:
###Lets do dot product two arrays
a=np.array([[11,12],[12,13]])
print(a)
b=np.array([[3,1,],[4,4]])
print("\n",b)
np.dot(a,b)


[[11 12]
 [12 13]]

 [[3 1]
 [4 4]]


array([[81, 59],
       [88, 64]])

In [60]:
###Lets Divide two arrays
a=np.array([[4,3,2,2],[2,3,3,4]])
print(a)
b=np.array([[3,1,4,2],[4,4,1,0]])
print("\n",b)
np.divide(a,b)


[[4 3 2 2]
 [2 3 3 4]]

 [[3 1 4 2]
 [4 4 1 0]]


C:\Users\admin\AppData\Local\Temp\ipykernel_2012\2759550187.py:6: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,b)


array([[1.33333333, 3.        , 0.5       , 1.        ],
       [0.5       , 0.75      , 3.        ,        inf]])

In [61]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.max())
print(data.min())
print(data.sum())


6
1
21


In [62]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))


[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


In [63]:
# Creating numpy array
data = np.array([10, 20, 30, 40, 50])

# calculating mean
mean = np.mean(data)
print("Mean:", mean)

# calculating median 
median = np.median(data)
print("Median:", median)

# calculating standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Calculating variance
variance = np.var(data)
print("Variance:", variance)

# calculating percentile
percentile_75 = np.percentile(data, 50)
print("75th Percentile:", percentile_75)


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Variance: 200.0
75th Percentile: 30.0


In [65]:
a= np.array([1,2,3,4,5])

# saving file in binary format
np.save('outfile',a)


In [66]:
# Loading file using load() method
b = np.load('outfile.npy')
print(b)


[1 2 3 4 5]


In [67]:
a = np.array([11,22,33,44,55])
# Saving file in text format using savetxt() method
np.savetxt('out.txt',a)

#loading text file using loadtxt() method
b = np.loadtxt('out.txt')
print(b)


[11. 22. 33. 44. 55.]
